---
title: "FinalProject"
author: "Pratyush Pant"
date: "11/26/2019"
output:
  pdf_document: default
  html_document: default
---

```{r}
meanData = read.csv("/Users/pratyushpant/Downloads/data_mean.csv", header = TRUE)
attach(meanData)
library(car)
str(meanData)
m1 = lm(diagnosis ~ radius_mean + texture_mean + perimeter_mean + area_mean + smoothness_mean + compactness_mean + 
          concavity_mean + concave.points_mean + symmetry_mean + fractal_dimension_mean, family = binomial)
summary(m1)
vif(m1)
cor(meanData)
plot(meanData)
par(mfrow=c(2,2))
par(mar = rep(2, 4))
plot(m1)
mmps(m1, layout = c(3,4))
```
Here we removed redundant parameters. Parameters with high VIF.
```{r}
m2 = glm(diagnosis ~ radius_mean + texture_mean + smoothness_mean + compactness_mean + 
           concavity_mean + concave.points_mean + symmetry_mean + fractal_dimension_mean, family = binomial())
summary(m2)
par(mfrow=c(4,2))
#plot(radius_mean,diagnosis)
#plot(texture_mean,diagnosis)
#plot(smoothness_mean,diagnosis)
#plot(compactness_mean,diagnosis)
#plot(concavity_mean,diagnosis)
#plot(concave.points_mean,diagnosis)
#plot(symmetry_mean,diagnosis)
#plot(fractal_dimension_mean,diagnosis)
```
Transformation to remove skewness in data
```{r}
logRadius = log(radius_mean)
logTexture = log(texture_mean)
logSmoothness = log(smoothness_mean)
logCompact = log(compactness_mean)
logConcavity = log(concavity_mean)
logConcave = log(concave.points_mean)
logSymmetry = log(symmetry_mean)
logFractal = log(fractal_dimension_mean)
m3 = glm(diagnosis ~ logRadius + logTexture + logSmoothness + logCompact + logConcavity + logConcave +
           logSymmetry + logFractal)
summary(m3)
mmps(m3, layout = c(3,3))
```
```{r}
mint = glm(diagnosis ~1)
forwardAIC = step(mint, scope = list(lower=~1, upper=~ logRadius + logTexture + logSmoothness 
            + logCompact + logConcavity + logConcave + logSymmetry + logFractal),direction="forward")
```
```{r}
#backwardBIC = step(m3,direction="backward", k = log(n))
```
```{r}
bothAIC = step(mint, scope = list(lower=~1, upper=~logRadius + logTexture + logSmoothness + logCompact + 
                                    logSymmetry + logFractal), direction="both")
```
```{r}
m4 = glm(diagnosis ~ logRadius + logTexture + logSmoothness + logSymmetry + logCompact)
summary(m4)
par(mfrow=c(2,2))
plot(m4)
mmps(m4, layout = c(2,3))
```
```{r}
meanData2 = meanData[-c(426, 556, 281),]
str(meanData2)
logRadius2 = log(meanData2$radius_mean)
logTexture2 = log(meanData2$texture_mean)
logSmoothness2 = log(meanData2$smoothness_mean)
logSymmetry2 = log(meanData2$symmetry_mean)
logCompact2 = log(meanData2$compactness_mean)
logConcavity2 = log(meanData2$concavity_mean)
logConcave2 = log(meanData2$concave.points_mean)
logFractal2 = log(meanData2$fractal_dimension_mean)
m5 = glm(diagnosis ~ logRadius2 + logTexture2 + logSmoothness2 + logSymmetry2 + logCompact2, data=meanData2)
summary(m5)
par(mfrow=c(2,2))
plot(m5)
mmps(m5, layout = c(2,3))
```
```{r}
m6 = glm(diagnosis ~ logRadius2 + logTexture2 + logSmoothness2 + logSymmetry2 + logCompact2 + 
           logSmoothness2:logCompact2, data = meanData2)
summary(m6)
par(mfrow=c(2,2))
plot(m6)
mmps(m6, layout = c(2,3))
anova(m5, m6)
```
```{r}
library(boot)
rownames(meanData2) = NULL
PMSE_10_fold_cv = NULL
for(i in 1:10){
  m5 = glm(diagnosis ~ log(radius_mean) + log(texture_mean) + log(smoothness_mean) + 
             log(symmetry_mean) + log(compactness_mean), data = meanData2)
  PMSE_10_fold_cv = cv.glm(meanData2, m5, K = 10)$delta[1]
}
PMSE_10_fold_cv
PMSE_10_fold_cv2 = NULL
for(i in 1:10){
  m6 = glm(diagnosis ~ log(radius_mean) + log(texture_mean) + log(smoothness_mean) + 
          log(symmetry_mean) + log(compactness_mean) + log(smoothness_mean):log(compactness_mean),
          data = meanData2)
  PMSE_10_fold_cv2 = cv.glm(meanData2, m6, K = 10)$delta[1]
}
PMSE_10_fold_cv2
```
```{r}
library(pROC)
m7 = roc(meanData2$diagnosis ~ fitted(m5))
plot(m7)
auc(m7)
```